Repository hugovk/tinytext, pull requests merged in 2020-10, with the labels that each got.

#56 Update pre-commit
  .pre-commit-config.yaml
Labels: automerge, changelog: Changed

#57 Migrate Travis CI to .com
  README.md
Labels: automerge, changelog: Changed

#59 Add Python 3.9 final to Travis CI
  .travis.yml
Labels: changelog: Changed, hacktoberfest-accepted, testing

#61 Support PyPy3
  .github/workflows/test.yml
  .travis.yml
  setup.py
  tox.ini
Labels: changelog: Added, testing
